trigger:
- main

pool:
  name: 'Deployment'  # Agente self-hosted con JDK, Gradle y Android SDK configurados

variables:
  buildConfiguration: 'release'
  apkOutputPath: 'app/build/outputs/apk/release'

steps:
# 1. Descargar el .jks desde Secure Files
- task: DownloadSecureFile@1
  name: DownloadKeystore
  inputs:
    secureFile: 'my-release-key.jks'  # <-- nombre exacto del archivo subido a Secure Files

# 2. Compilar el APK con firma
- task: Gradle@2
  displayName: 'Compilar APK firmado (release)'
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4096m'
    publishJUnitResults: false
    tasks: 'assembleRelease'
  env:
    android.injected.signing.store.file: '$(DownloadKeystore.secureFilePath)'
    android.injected.signing.store.password: '$(keystorePassword)'
    android.injected.signing.key.alias: '$(keyAlias)'
    android.injected.signing.key.password: '$(keyPassword)'

# 3. Publicar el APK firmado como artefacto
- task: PublishBuildArtifacts@1
  displayName: 'Publicar APK firmado como artefacto'
  inputs:
    pathToPublish: '$(apkOutputPath)'
    artifactName: 'SignedAPK'
    publishLocation: 'Container'
