name: Build and Sign APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate Signed APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > EssencyStockMovementMobileAppKotlin/essency-release-key.jks

    - name: Build Signed APK
      working-directory: EssencyStockMovementMobileAppKotlin
      run: |
        ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=essency-release-key.jks \
        -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
        -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
        -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EssencyStockMovement-release-apk
        path: EssencyStockMovementMobileAppKotlin/app/build/outputs/apk/release/*.apk
